---
name: Symfony
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "!ChangeMe!"
          POSTGRES_PORT: 5432
          POSTGRES_USER: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: don't use .env.test
        run: mv .env.test .tmp
      - name: Install Dependencies
        run: php composer.phar install -q --no-ansi --no-interaction --no-scripts
          --no-progress --prefer-dist
      - name: Execute a migration to a specified version or the latest available
          version.
        run: bin/console doctrine:migrations:migrate
      - name: Run Unit Tests
        run: XDEBUG_MODE_COVERAGE=coverage vendor/bin/phpunit


